module.exports = {
  // listeners
  BROADCAST_GAME_START: 'BROADCAST_GAME_START',
  BROADCAST_JOINED_GAME: 'BROADCAST_JOINED_GAME',
  JOIN_TEAM_ROOM: 'JOIN_TEAM_ROOM',
  LEAVE_TEAM_ROOM: 'LEAVE_TEAM_ROOM',
  ENTER_GEOFENCE: 'ENTER_GEOFENCE',
  EXIT_GEOFENCE: 'EXIT_GEOFENCE',
  BROADCAST_TASK_COMPLETE: 'BROADCAST_TASK_COMPLETE',
  BROADCAST_END_GAME: 'BROADCAST_END_GAME',

  // emitters
  GAME_START: 'GAME_START',
  JOINED_GAME: 'JOINED_GAME',
  CONFIRM_TEAM_PRESENCE: 'CONFIRM_TEAM_PRESENCE',
  COMPLETE_TASK: 'COMPLETE_TASK',
  END_GAME: 'END_GAME'
}
