module.exports = {
  // listeners
  BROADCAST_GAME_START: 'BROADCAST_GAME_START',
  BROADCAST_JOINED_GAME: 'BROADCAST_JOINED_GAME',
  JOIN_TEAM_ROOM: 'JOIN_TEAM_ROOM',
  LEAVE_TEAM_ROOM: 'LEAVE_TEAM_ROOM',

  // emitters
  GAME_START: 'GAME_START',
  JOINED_GAME: 'JOINED_GAME'
}
